<script setup lang="ts">
const vigenere =
` ABCDEFGHIJKLMNOPQRSTUVWXYZABCD
AKRYPTOSABCDEFGHIJLMNQUVWXZKRYP
BRYPTOSABCDEFGHIJLMNQUVWXZKRYPT
CYPTOSABCDEFGHIJLMNQUVWXZKRYPTO
DPTOSABCDEFGHIJLMNQUVWXZKRYPTOS
ETOSABCDEFGHIJLMNQUVWXZKRYPTOSA
FOSABCDEFGHIJLMNQUVWXZKRYPTOSAB
GSABCDEFGHIJLMNQUVWXZKRYPTOSABC
HABCDEFGHIJLMNQUVWXZKRYPTOSABCD
IBCDEFGHIJLMNQUVWXZKRYPTOSABCDE
JCDEFGHIJLMNQUVWXZKRYPTOSABCDEF
KDEFGHIJLMNQUVWXZKRYPTOSABCDEFG
LEFGHIJLMNQUVWXZKRYPTOSABCDEFGH
MFGHIJLMNQUVWXZKRYPTOSABCDEFGHI
NGHIJLMNQUVWXZKRYPTOSABCDEFGHIJL
OHIJLMNQUVWXZKRYPTOSABCDEFGHIJL
PIJLMNQUVWXZKRYPTOSABCDEFGHIJLM
QJLMNQUVWXZKRYPTOSABCDEFGHIJLMN
RLMNQUVWXZKRYPTOSABCDEFGHIJLMNQ
SMNQUVWXZKRYPTOSABCDEFGHIJLMNQU
TNQUVWXZKRYPTOSABCDEFGHIJLMNQUV
UQUVWXZKRYPTOSABCDEFGHIJLMNQUVW
VUVWXZKRYPTOSABCDEFGHIJLMNQUVWX
WVWXZKRYPTOSABCDEFGHIJLMNQUVWXZ
XWXZKRYPTOSABCDEFGHIJLMNQUVWXZK
YXZKRYPTOSABCDEFGHIJLMNQUVWXZKR
ZZKRYPTOSABCDEFGHIJLMNQUVWXZKRY
 ABCDEFGHIJKLMNOPQRSTUVWXYZABCD
`;
</script>

<template>
<article>
<pre>
<span id="k1"><NuxtLink to="/k1">{{ k[1] }}</NuxtLink></span>
<span id="k2"><NuxtLink to="/k2">{{ k[2] }}</NuxtLink></span>
<span id="k3"><NuxtLink to="/k3">{{ k[3] }}</NuxtLink></span><span id="k4"><NuxtLink to="/k4">{{ k[4] }}</NuxtLink></span>
</pre>
<pre>{{ vigenere }}</pre>
</article>
</template>

<style scoped>
a {
 color: unset;
}


article {
  display: flex;
  flex-flow: row nowrap;
  justify-content: space-evenly;
}

article > pre {
  font-size: 2rem;
}

pre > span {
  transition: color 0.4s linear;
}

pre > span#k1:hover {
  color: crimson;
}

pre > span#k2:hover {
  color: green;
}

pre > span#k3:hover {
  color: peru;
}

pre > span#k4:hover {
  color: deepskyblue;
}
</style>
